### ISSUE TITLE
undeclared identifier: 'CFArrayGetTypeId'

### ISSUE THREAD

**Issue by teras** [yglukhov/plists#1]
Hello
I am trying to use plists, but compiling fails with the following error:

```
/Users/teras/.nimble/pkgs/plists-0.2.0/plists.nim(41, 19) Error: undeclared identifier: 'CFArrayGetTypeId'
```

It seems that somehow it is not possible to find the declaration of `CFArrayGetTypeId`, probably because the `import darwin/core_foundation` is not properly parsed?

I am using:
 * macOS 10.15.3 
 * Xcode 11.4
 * clang 11.0.3

**Comment by yglukhov** [comment]
Please make sure `darwin` dependency is latest version.

**Comment by teras** [comment]
Thank you for the bliz-fast response.

This is the results when I install plists:

```
» nimble  install plists                                                                                                               23:38:55
Downloading https://github.com/yglukhov/plists using git
  Verifying dependencies for plists@0.2.0
      Info: Dependency on https://github.com/yglukhov/darwin@any version already satisfied
  Verifying dependencies for darwin@0.1.0
 Installing plists@0.2.0
    Prompt: plists@0.2.0 already exists. Overwrite? [y/N]
    Answer: y
   Warning: Cannot completely remove /Users/teras/.nimble/pkgs/plists-0.2.0. Files not installed by nimble are present.
   Warning: No .nimble or .nimble-link file found for /Users/teras/.nimble/pkgs/plists-0.2.0
   Success: plists installed successfully.
```

There seems to install darwin 0.1.0 by default. Should I specifically do something?

**Comment by teras** [comment]
... and this when I remove the `~/.nimble/pkgs/plists-0.2.0/` folder:

```
» nimble  install plists                                                                                                               23:41:07
Downloading https://github.com/yglukhov/plists using git
  Verifying dependencies for plists@0.2.0
      Info: Dependency on https://github.com/yglukhov/darwin@any version already satisfied
  Verifying dependencies for darwin@0.1.0
 Installing plists@0.2.0
   Success: plists installed successfully.
```

**Comment by yglukhov** [comment]
Remove `~/.nimble/pkgs/darwin*` and reinstall plists again

**Comment by teras** [comment]
Woohooo!!! it works!
**Thank you!**

Maybe, document this somewhere? Probably I won't be the first person who might have this issue?

**Comment by yglukhov** [comment]
Meh, it's a pretty default workflow to update your dependencies when there's something fishy about them :)

**Comment by teras** [comment]
👍
